//! Human-readable integration plan (FR-092).

use crate::manifest::Manifest;
use ovid_world::WorldLock;

/// Render `integration-plan.md` from a manifest and its world lock.
pub fn integration_plan_markdown(manifest: &Manifest, lock: Option<&WorldLock>) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# Integration plan — {}\n\nRevision `{}` · analysis `{}` · generated by ovid {}\n\n",
        manifest.repository.canonical_url,
        manifest.repository.revision,
        manifest.metadata.analysis_id,
        manifest.metadata.ovid_version
    ));

    out.push_str("## Workloads\n\n");
    if manifest.workloads.is_empty() {
        out.push_str("_No workloads were executed (inventory-only analysis)._\n\n");
    }
    for workload in &manifest.workloads {
        out.push_str(&format!(
            "- **{}** — `{}` — success: {} — status: **{}**\n",
            workload.name,
            workload.command.join(" "),
            workload.success_predicate,
            workload.status
        ));
    }
    out.push('\n');

    out.push_str("## External dependencies\n\n");
    if manifest.external_systems.is_empty() {
        out.push_str("_No external systems were observed for the executed workloads._\n\n");
    } else {
        out.push_str("| Dependency | Protocol | Causality | Treatment | Outcomes |\n");
        out.push_str("|---|---|---|---|---|\n");
        for system in &manifest.external_systems {
            out.push_str(&format!(
                "| {} (`{}:{}`) | {} | {} | {} | {} |\n",
                system.id,
                system.address,
                system.port,
                system.protocol,
                system
                    .causality
                    .map(|c| format!("{c:?}"))
                    .unwrap_or_else(|| "unknown".into()),
                system.treatment.as_deref().unwrap_or("none"),
                system.outcomes.join(", ")
            ));
        }
        out.push('\n');
    }

    if let Some(lock) = lock {
        out.push_str("## Startup order\n\n");
        for (index, cell) in lock.startup_order.iter().enumerate() {
            out.push_str(&format!("{}. {cell}\n", index + 1));
        }
        out.push_str(&format!(
            "\nWorld status: **{:?}** · digest `{}`\n\n",
            lock.status, lock.metadata.digest
        ));
    }

    out.push_str("## Unresolved\n\n");
    if manifest.unresolved.is_empty() {
        out.push_str("_Nothing unresolved for the executed workloads._\n\n");
    }
    for item in &manifest.unresolved {
        out.push_str(&format!("- **{}** — {}\n", item.id, item.reason));
    }

    out.push_str("\n## Limitations\n\n");
    if manifest.completeness.limitations.is_empty() {
        out.push_str("_None recorded._\n");
    }
    for limitation in &manifest.completeness.limitations {
        out.push_str(&format!("- {limitation}\n"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::{Manifest, RepositorySection, UnresolvedItem};
    use ovid_core::Digest;

    #[test]
    fn plan_renders_all_sections() {
        let mut manifest = Manifest::new(
            "analysis:x".into(),
            "observe",
            RepositorySection {
                canonical_url: "https://github.com/acme/app".into(),
                revision: "abc".into(),
                ref_requested: None,
                source_digest: Digest::of_bytes(b"t"),
                file_count: 1,
                total_size_bytes: 1,
            },
        );
        manifest.unresolved.push(UnresolvedItem {
            id: "telemetry.internal".into(),
            reason: "unclassified protocol".into(),
            evidence: vec![],
        });
        manifest
            .completeness
            .limitations
            .push("dynamic analysis limited to build workload".into());
        let markdown = integration_plan_markdown(&manifest, None);
        assert!(markdown.contains("# Integration plan"));
        assert!(markdown.contains("telemetry.internal"));
        assert!(markdown.contains("dynamic analysis limited"));
        assert!(markdown.contains("inventory-only") || markdown.contains("No workloads"));
    }
}
